name: textlint

on:
  push:
    branches:
      - 'article/**'
  pull_request:
    branches:
      - main

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Install textlint
        run: >
          npm i -D
          textlint
          textlint-filter-rule-allowlist
          textlint-rule-preset-ja-spacing
          textlint-rule-preset-ja-technical-writing
          textlint-rule-prh
          textlint-rule-spellcheck-tech-word

      - name: Install modules
        run: npm i

      - name: Run textlint
        run: npx textlint articles/*.md
